edition = "2018"

brace_style                     = "AlwaysNextLine"
color                           = "Always"
combine_control_expr            = true
condense_wildcard_suffixes      = false
control_brace_style             = "AlwaysNextLine"
empty_item_single_line          = false
fn_args_layout                  = "Vertical"
fn_params_layout                = "Vertical"
fn_single_line                  = false
force_multiline_blocks          = true
format_code_in_doc_comments     = true
format_macro_matchers           = true
format_macro_bodies             = true
format_strings                  = true
hard_tabs                       = false
imports_indent                  = "Block"
imports_layout                  = "Vertical"
indent_style                    = "Visual"
inline_attribute_width          = 80
imports_granularity             = "Item"
match_arm_leading_pipes         = "Always"
match_block_trailing_comma      = false
max_width                       = 80
merge_derives                   = false
merge_imports                   = false
normalize_comments              = true
normalize_doc_attributes        = true
overflow_delimited_expr         = true
remove_nested_parens            = true
reorder_impl_items              = true
reorder_imports                 = true
reorder_modules                 = true
space_after_colon               = true
space_before_colon              = true
spaces_around_ranges            = true
struct_lit_single_line          = false
tab_spaces                      = 2
trailing_comma                  = "Never"
trailing_semicolon              = true
type_punctuation_density        = "Wide"
use_field_init_shorthand        = false
use_try_shorthand               = false
where_single_line               = true
wrap_comments                   = true
